language: node_js

sudo: false

cache:
  directories:
    - node_modules
    - bower_components

before_install:
  - npm config set spin false
  - npm install -g npm@^2

install:
  - npm install
  - bower install

script:
  - jshint . && npm test
