language: node_js

sudo: false

cache:
  directories:
    - node_modules
    - bower_components

install:
  - npm install -g bower@1.3.12 jshint@2.5.10
  - npm install
  - bower install

script:
  - 'jshint . && npm test'
